name: Fetch HN Side Projects

on:
  workflow_dispatch:  # Manual trigger
  schedule:
    - cron: '0 */12 * * *'  # Run every 12 hours

jobs:
  fetch-hn:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install feedparser
    
    - name: Set script permissions
      run: chmod +x ${{ github.workspace }}/scripts/hn_side_projects.py
    
    - name: Run HN fetcher
      run: python ${{ github.workspace }}/scripts/hn_side_projects.py 
